spring:
  application:
    name: mozika

  datasource:
    url: jdbc:postgresql://localhost:5432/musical_app
    username: postgres
    password: 3198
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: antoniabijourasoarimalala@gmail.com
    password: kadd ohmz ltfx ahnw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


server:
  port: 8087
  servlet:
    context-path: /mozika

# Logs Configuration
logging:
  level:
    root: INFO                      
    org.mozika: DEBUG              
    org.hibernate.SQL: DEBUG       
    org.hibernate.type.descriptor.sql.BasicBinder:





mapi:
  base-url: https://messaging.mapi.mg/api
  username: kaloy123
  password: "hZ7Z8zrP:4.!9Rj"
  sender-id: KALOY

app:
  config:
    column-visibility:
      file: ${user.dir}/config/column-visibility.json
  jwt:
    secret: dGhpc2lzYXZlcnlsb25nc2VjcmV0a2V5Zm9ya2Fsb3liYWNrZW5kYXV0aHNlY3JldA==
    expiration-ms: 86400000
