-- ============================================================
-- MUSIC APP - PostgreSQL
-- Version sans ENUM
-- Les anciennes valeurs ENUM sont remplacées par des tables
-- de référence avec des clés étrangères.
-- ============================================================

-- ============================================================
-- 1. TABLES DE REFERENCE
-- ============================================================

CREATE TABLE "user_roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "user_roles" ("name") VALUES
('CLIENT'),
('ARTIST'),
('ADMIN');


CREATE TABLE "user_statuses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "user_statuses" ("name") VALUES
('ACTIVE'),
('INACTIVE'),
('BANNED'),
('SUSPENDED');


CREATE TABLE "audio_storage_types" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "audio_storage_types" ("name") VALUES
('DATABASE'),
('EXTERNAL_LINK');


CREATE TABLE "artist_types" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "artist_types" ("name") VALUES
('SOLO'),
('GROUP');


CREATE TABLE "verification_channels" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "verification_channels" ("name") VALUES
('EMAIL'),
('SMS');


CREATE TABLE "verification_statuses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "verification_statuses" ("name") VALUES
('PENDING'),
('VALIDATED'),
('REJECTED');


CREATE TABLE "member_statuses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "member_statuses" ("name") VALUES
('ACTIVE'),
('FORMER');


CREATE TABLE "event_moderation_statuses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "event_moderation_statuses" ("name") VALUES
('PENDING'),
('APPROVED'),
('REJECTED');


CREATE TABLE "participation_statuses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "participation_statuses" ("name") VALUES
('PENDING'),
('CONFIRMED'),
('DECLINED');


CREATE TABLE "media_types" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "media_types" ("name") VALUES
('PHOTO'),
('VIDEO');


CREATE TABLE "interaction_targets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "interaction_targets" ("name") VALUES
('EVENT'),
('CONCERT'),
('MEDIA'),
('SONG'),
('COMMENT');


CREATE TABLE "report_statuses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "report_statuses" ("name") VALUES
('PENDING'),
('REVIEWED'),
('DISMISSED'),
('ACTIONED');


CREATE TABLE "playlist_visibilities" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "playlist_visibilities" ("name") VALUES
('PRIVATE'),
('PUBLIC');


CREATE TABLE "play_modes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "play_modes" ("name") VALUES
('AUDIO'),
('VIDEO');


CREATE TABLE "notification_types" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "notification_types" ("name") VALUES
('NEW_RELEASE'),
('EVENT_REMINDER'),
('EVENT_INVITATION'),
('CONCERT_INVITATION'),
('COMMENT_REPLY'),
('FOLLOW'),
('VERIFICATION');


CREATE TABLE "submission_statuses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO "submission_statuses" ("name") VALUES
('PENDING'),
('PROCESSING'),
('SUCCESS'),
('ERROR');


-- ============================================================
-- 2. UTILISATEURS  
-- ============================================================


CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR(255) UNIQUE,
  "phone" VARCHAR(20) UNIQUE,
  "email_verified_at" TIMESTAMP,
  "phone_verified_at" TIMESTAMP,
  "password_hash" VARCHAR(255) NOT NULL,
  "role_id" BIGINT NOT NULL,
  "status_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("role_id") REFERENCES "user_roles" ("id"),
  FOREIGN KEY ("status_id") REFERENCES "user_statuses" ("id"),

  CONSTRAINT "ck_users_contact"
    CHECK ("email" IS NOT NULL OR "phone" IS NOT NULL)
);
 =======================================
 -- Pour le Client seulement
 =======================================
CREATE TABLE "users_infos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) ,
  "last_name" VARCHAR(255),
  "user_name" VARCHAR(255) UNIQUE,
  "id_user" BIGINT NOT NULL,
  FOREIGN KEY("id_user") REFERENCES "users" ("id")
);

CREATE TABLE "user_status_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "previous_status_id" BIGINT,
  "new_status_id" BIGINT NOT NULL,
  "reason" TEXT,
  "changed_by_user_id" BIGINT,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("previous_status_id") REFERENCES "user_statuses" ("id"),
  FOREIGN KEY ("new_status_id") REFERENCES "user_statuses" ("id"),
  FOREIGN KEY ("changed_by_user_id") REFERENCES "users" ("id")
);


CREATE TABLE "verification_codes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "channel_id" BIGINT NOT NULL,
  "destination" VARCHAR(255) NOT NULL,
  "code" VARCHAR(10) NOT NULL,
  "expires_at" TIMESTAMP NOT NULL,
  "consumed_at" TIMESTAMP,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("channel_id") REFERENCES "verification_channels" ("id")
);


CREATE TABLE "clients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT UNIQUE NOT NULL,

  FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);


-- ============================================================
-- 3. ARTISTES
-- ============================================================

CREATE TABLE "genres" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);


CREATE TABLE "artists" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT UNIQUE NOT NULL,
  "artist_type_id" BIGINT NOT NULL,
  "stage_name" VARCHAR(100) NOT NULL,
  "active_since_year" INT,
  "photo_url" TEXT,
  "bio" TEXT,
  "verification_status_id" BIGINT NOT NULL,
  "verified_at" TIMESTAMP,
  "is_certified" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("artist_type_id") REFERENCES "artist_types" ("id"),
  FOREIGN KEY ("verification_status_id") REFERENCES "verification_statuses" ("id")
);


CREATE TABLE "instrument_roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label" VARCHAR(50) UNIQUE NOT NULL
);


CREATE TABLE "artist_group_members" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_artist_id" BIGINT NOT NULL,
  "member_artist_id" BIGINT,
  "full_name" VARCHAR(100),
  "role_instrument_id" BIGINT,
  "photo_url" TEXT,
  "status_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("group_artist_id") REFERENCES "artists" ("id"),
  FOREIGN KEY ("member_artist_id") REFERENCES "artists" ("id"),
  FOREIGN KEY ("role_instrument_id") REFERENCES "instrument_roles" ("id"),
  FOREIGN KEY ("status_id") REFERENCES "member_statuses" ("id")
);


-- ============================================================
-- 4. CATALOGUE MUSICAL
-- ============================================================

CREATE TABLE "albums" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "artist_id" BIGINT NOT NULL,
  "title" VARCHAR(150) NOT NULL,
  "cover_url" TEXT,
  "release_date" DATE,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("artist_id") REFERENCES "artists" ("id")
);


CREATE TABLE "songs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "artist_id" BIGINT NOT NULL,
  "album_id" BIGINT,
  "title" VARCHAR(150) NOT NULL,
  "duration_seconds" INT,
  "release_date" DATE,
  "language" VARCHAR(10) NOT NULL DEFAULT 'fr',
  "author_composer" VARCHAR(255),
  "musical_arranger" VARCHAR(255),
  "recording_location" VARCHAR(255),
  "recording_date" DATE,
  "storage_type_id" BIGINT NOT NULL,
  "audio_url" TEXT,
  "audio_file" BYTEA,
  "video_url" TEXT,
  "karaoke_audio" BYTEA,
  "lyrics" TEXT,
  "lyrics_sync_data" JSONB,
  "solfa" TEXT,
  "playback" BYTEA,
  "is_downloadable" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("artist_id") REFERENCES "artists" ("id"),
  FOREIGN KEY ("album_id") REFERENCES "albums" ("id"),
  FOREIGN KEY ("storage_type_id") REFERENCES "audio_storage_types" ("id"),

  CONSTRAINT "ck_songs_duration"
    CHECK ("duration_seconds" IS NULL OR "duration_seconds" > 0)
);


CREATE TABLE "song_genres" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "song_id" BIGINT NOT NULL,
  "genre_id" BIGINT NOT NULL,

  FOREIGN KEY ("song_id") REFERENCES "songs" ("id"),
  FOREIGN KEY ("genre_id") REFERENCES "genres" ("id")
);


CREATE UNIQUE INDEX "uq_song_genres_song_genre"
ON "song_genres" ("song_id", "genre_id");


-- ============================================================
-- 5. EVENEMENTS ET CONCERTS
-- ============================================================

CREATE TABLE "events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(150) NOT NULL,
  "description" TEXT,
  "start_date" DATE NOT NULL,
  "end_date" DATE NOT NULL,
  "created_by_artist_id" BIGINT NOT NULL,
  "moderation_status_id" BIGINT NOT NULL,
  "reviewed_at" TIMESTAMP,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("created_by_artist_id") REFERENCES "artists" ("id"),
  FOREIGN KEY ("moderation_status_id") REFERENCES "event_moderation_statuses" ("id"),

  CONSTRAINT "ck_events_dates"
    CHECK ("end_date" >= "start_date")
);


CREATE TABLE "venues" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(150) NOT NULL,
  "location" VARCHAR(255)
);


CREATE TABLE "concerts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" BIGINT,
  "title" VARCHAR(150),
  "description" TEXT,
  "artist_id" BIGINT NOT NULL,
  "venue_id" BIGINT,
  "start_time" TIMESTAMP NOT NULL,
  "end_time" TIMESTAMP,
  "status_id" BIGINT NOT NULL,
  "responded_at" TIMESTAMP,
  "created_by_artist_id" BIGINT NOT NULL,
  "moderation_status_id" BIGINT NOT NULL,
  "reviewed_at" TIMESTAMP,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("event_id") REFERENCES "events" ("id"),
  FOREIGN KEY ("artist_id") REFERENCES "artists" ("id"),
  FOREIGN KEY ("venue_id") REFERENCES "venues" ("id"),
  FOREIGN KEY ("status_id") REFERENCES "participation_statuses" ("id"),
  FOREIGN KEY ("created_by_artist_id") REFERENCES "artists" ("id"),
  FOREIGN KEY ("moderation_status_id") REFERENCES "event_moderation_statuses" ("id")
);


CREATE INDEX "ix_concerts_event_artist"
ON "concerts" ("event_id", "artist_id");


CREATE TABLE "event_media" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" BIGINT NOT NULL,
  "uploader_user_id" BIGINT NOT NULL,
  "media_type_id" BIGINT NOT NULL,
  "url" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("event_id") REFERENCES "events" ("id"),
  FOREIGN KEY ("uploader_user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("media_type_id") REFERENCES "media_types" ("id")
);


-- ============================================================
-- 6. INTERACTIONS SOCIALES
-- ============================================================

CREATE TABLE "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "author_user_id" BIGINT NOT NULL,
  "target_type_id" BIGINT NOT NULL,
  "target_id" BIGINT NOT NULL,
  "content" TEXT NOT NULL,
  "is_hidden" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("author_user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("target_type_id") REFERENCES "interaction_targets" ("id")
);


CREATE TABLE "likes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "target_type_id" BIGINT NOT NULL,
  "target_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("target_type_id") REFERENCES "interaction_targets" ("id")
);


CREATE UNIQUE INDEX "uq_likes_user_target"
ON "likes" ("user_id", "target_type_id", "target_id");


CREATE TABLE "reports" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reporter_user_id" BIGINT NOT NULL,
  "target_type_id" BIGINT NOT NULL,
  "target_id" BIGINT NOT NULL,
  "reason" TEXT,
  "status_id" BIGINT NOT NULL,
  "reviewed_at" TIMESTAMP,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("reporter_user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("target_type_id") REFERENCES "interaction_targets" ("id"),
  FOREIGN KEY ("status_id") REFERENCES "report_statuses" ("id")
);


CREATE TABLE "follows" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_user_id" BIGINT NOT NULL,
  "artist_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("client_user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("artist_id") REFERENCES "artists" ("id")
);


CREATE UNIQUE INDEX "uq_follows_client_artist"
ON "follows" ("client_user_id", "artist_id");


-- ============================================================
-- 7. PLAYLISTS
-- ============================================================

CREATE TABLE "playlists" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_user_id" BIGINT NOT NULL,
  "name" VARCHAR(150) NOT NULL,
  "visibility_id" BIGINT NOT NULL,
  "share_token" VARCHAR(64) UNIQUE,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("owner_user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("visibility_id") REFERENCES "playlist_visibilities" ("id")
);


CREATE TABLE "playlist_songs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "playlist_id" BIGINT NOT NULL,
  "song_id" BIGINT NOT NULL,
  "position" INT NOT NULL,
  "added_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("playlist_id") REFERENCES "playlists" ("id"),
  FOREIGN KEY ("song_id") REFERENCES "songs" ("id")
);


CREATE UNIQUE INDEX "uq_playlist_songs_playlist_song"
ON "playlist_songs" ("playlist_id", "song_id");


CREATE TABLE "editorial_playlists" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "artist_id" BIGINT NOT NULL,
  "title" VARCHAR(150) NOT NULL,
  "description" TEXT,
  "cover_url" TEXT,
  "is_featured" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("artist_id") REFERENCES "artists" ("id")
);


CREATE TABLE "editorial_playlist_songs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "editorial_playlist_id" BIGINT NOT NULL,
  "song_id" BIGINT NOT NULL,
  "position" INT NOT NULL,

  FOREIGN KEY ("editorial_playlist_id") REFERENCES "editorial_playlists" ("id"),
  FOREIGN KEY ("song_id") REFERENCES "songs" ("id")
);


CREATE UNIQUE INDEX "uq_editorial_playlist_songs_playlist_song"
ON "editorial_playlist_songs" ("editorial_playlist_id", "song_id");


-- ============================================================
-- 8. ECOUTE / HISTORIQUE / TELECHARGEMENTS
-- ============================================================

CREATE TABLE "listening_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "song_id" BIGINT NOT NULL,
  "play_mode_id" BIGINT NOT NULL,
  "listened_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("song_id") REFERENCES "songs" ("id"),
  FOREIGN KEY ("play_mode_id") REFERENCES "play_modes" ("id")
);


CREATE TABLE "up_next_queue" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "song_id" BIGINT NOT NULL,
  "position" INT NOT NULL,
  "added_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("song_id") REFERENCES "songs" ("id")
);


CREATE TABLE "downloads" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "playlist_id" BIGINT NOT NULL,
  "downloaded_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "expires_at" TIMESTAMP NOT NULL,

  FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("playlist_id") REFERENCES "playlists" ("id")
);


CREATE UNIQUE INDEX "uq_downloads_user_playlist"
ON "downloads" ("user_id", "playlist_id");


CREATE TABLE "search_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "query_text" VARCHAR(255) NOT NULL,
  "searched_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);


-- ============================================================
-- 9. NOTIFICATIONS
-- ============================================================

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "type_id" BIGINT NOT NULL,
  "content" TEXT NOT NULL,
  "related_entity_type_id" BIGINT,
  "related_entity_id" BIGINT,
  "is_read" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),

  FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("type_id") REFERENCES "notification_types" ("id"),
  FOREIGN KEY ("related_entity_type_id") REFERENCES "interaction_targets" ("id")
);


CREATE TABLE "notification_preferences" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "notification_type_id" BIGINT NOT NULL,
  "is_enabled" BOOLEAN NOT NULL DEFAULT TRUE,

  FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("notification_type_id") REFERENCES "notification_types" ("id")
);


CREATE UNIQUE INDEX "uq_notification_preferences_user_type"
ON "notification_preferences" ("user_id", "notification_type_id");


-- ============================================================
-- 10. IMPORT / TRAITEMENT DE CONTENU
-- ============================================================

CREATE TABLE "content_submissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "artist_id" BIGINT NOT NULL,
  "source_filename" VARCHAR(255) NOT NULL,
  "file_type" VARCHAR(20) NOT NULL,
  "status_id" BIGINT NOT NULL,
  "error_message" TEXT,
  "submitted_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "processed_at" TIMESTAMP,

  FOREIGN KEY ("artist_id") REFERENCES "artists" ("id"),
  FOREIGN KEY ("status_id") REFERENCES "submission_statuses" ("id")
);


-- ============================================================
-- 11. COMMENTAIRES DOCUMENTAIRES
-- ============================================================

COMMENT ON TABLE "users"
IS 'Un utilisateur doit avoir au moins un email ou un numéro de téléphone.';

COMMENT ON COLUMN "verification_codes"."destination"
IS 'Email ou téléphone utilisé au moment de l envoi.';

COMMENT ON TABLE "artists"
IS 'Les champs communs sont utilisés pour les artistes solo et les groupes.';

COMMENT ON COLUMN "artists"."active_since_year"
IS 'Solo : année de début de carrière. Groupe : année de formation.';

COMMENT ON COLUMN "artist_group_members"."group_artist_id"
IS 'ID du groupe dont cet artiste est membre.';

COMMENT ON COLUMN "artist_group_members"."member_artist_id"
IS 'ID de l artiste s il possède son propre compte.';

COMMENT ON COLUMN "artist_group_members"."full_name"
IS 'Nom de la personne si elle ne possède pas de compte.';

COMMENT ON COLUMN "songs"."duration_seconds"
IS 'Durée de la chanson en secondes.';

COMMENT ON COLUMN "songs"."language"
IS 'Langue de la chanson, pré-remplie par le programme.';

COMMENT ON COLUMN "songs"."storage_type_id"
IS 'Référence vers audio_storage_types : DATABASE ou EXTERNAL_LINK.';

COMMENT ON COLUMN "songs"."audio_url"
IS 'URL vers le fichier audio lorsque le stockage est externe.';

COMMENT ON COLUMN "songs"."audio_file"
IS 'Fichier audio sauvegardé directement dans la base si applicable.';

COMMENT ON COLUMN "songs"."lyrics"
IS 'Texte des paroles sauvegardé directement dans la base.';

COMMENT ON TABLE "events"
IS 'Un événement peut contenir plusieurs concerts.';

COMMENT ON TABLE "concerts"
IS 'Un concert peut être autonome ou lié à un événement.';

COMMENT ON COLUMN "concerts"."event_id"
IS 'NULL si le concert est indépendant.';

COMMENT ON COLUMN "concerts"."title"
IS 'Optionnel, surtout utile pour un concert indépendant.';

COMMENT ON COLUMN "concerts"."artist_id"
IS 'Artiste ou groupe participant au concert.';

COMMENT ON COLUMN "concerts"."status_id"
IS 'Référence vers participation_statuses.';

COMMENT ON COLUMN "concerts"."created_by_artist_id"
IS 'Artiste organisateur du concert ou de l événement.';

COMMENT ON TABLE "comments"
IS 'La cible est identifiée par target_type_id + target_id.';

COMMENT ON TABLE "likes"
IS 'La cible est identifiée par target_type_id + target_id.';

COMMENT ON TABLE "reports"
IS 'La cible est identifiée par target_type_id + target_id.';

-- ============================================================
-- FIN DU SCRIPT
-- ============================================================
