-- ---------------------------------------------------------------------
-- Resynchronisation des sequences d'identite
--
-- POURQUOI CE SCRIPT EXISTE
--
-- Les scripts de peuplement inserent des identifiants explicites (401 pour un
-- evenement, 718 pour un concert, etc.) afin que les donnees de test soient
-- lisibles et rejouables. Or PostgreSQL n'avance PAS le compteur d'une colonne
-- GENERATED BY DEFAULT AS IDENTITY quand on lui impose une valeur.
--
-- Consequence : le compteur reste derriere. Le jour ou l'application cree une
-- ligne elle-meme, PostgreSQL propose un identifiant deja pris et refuse
-- l'insertion :
--
--   ERREUR: la valeur d'une cle dupliquee rompt la contrainte unique
--           « concerts_pkey ». La cle (id)=(718) existe deja.
--
-- Le symptome est trompeur : le backend traduit cette erreur en
-- « Un compte existe deja avec ces informations », message qui n'a aucun
-- rapport avec la situation.
--
-- QUAND LE LANCER
--
-- Apres chaque execution d'un script de peuplement, et avant tout test d'une
-- fonctionnalite qui cree des donnees depuis l'application.
--
--   psql -U postgres -d musical_app -f resynchroniser_sequences.sql
--
-- Le script traite toutes les tables d'un coup plutot qu'une liste figee :
-- une table ajoutee plus tard sera couverte sans qu'on ait a y penser.
-- ---------------------------------------------------------------------

DO $$
DECLARE
    ligne RECORD;
    plus_grand BIGINT;
BEGIN
    FOR ligne IN
        SELECT c.table_name, c.column_name,
               pg_get_serial_sequence(c.table_name, c.column_name) AS sequence
        FROM information_schema.columns c
        WHERE c.table_schema = 'public'
          AND c.is_identity = 'YES'
          AND pg_get_serial_sequence(c.table_name, c.column_name) IS NOT NULL
    LOOP
        EXECUTE format('SELECT coalesce(max(%I), 0) FROM %I', ligne.column_name, ligne.table_name)
            INTO plus_grand;

        -- is_called = true : le prochain appel renverra plus_grand + 1.
        -- Sur une table vide, on repart a 1 sans le marquer comme consomme.
        IF plus_grand > 0 THEN
            PERFORM setval(ligne.sequence, plus_grand, true);
        ELSE
            PERFORM setval(ligne.sequence, 1, false);
        END IF;

        RAISE NOTICE 'sequence % alignee sur %', ligne.sequence, plus_grand;
    END LOOP;
END $$;
